version: "3"

services:
  catcat-webhook:
    container_name: catcat-webhook
    env_file: .env
    environment:
      - PORT=${PORT:-9090}
    image: catcatio/catcat-webhook
    working_dir: /usr/app
    ports:
      - "${PORT:-9090}:${PORT:-9090}"
    volumes:
      - ../:/usr/app
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:${LS_PORT:-12201}
        tag: "catcat-webhook"
    command: npm run init
